@baseURL = http://localhost:3333
@token = b8b7b5d9-ee2e-4580-ab77-b3092a93a409

POST {{baseURL}}/chat
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "message": "Olá, estamos iniciando uma conversa. Meu nome é Renan, quem é você?"
}